include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - avoid_slow_async_io
    - unnecessary_brace_in_string_interps
    #- hash_and_equals
    - unnecessary_await_in_return
    - unnecessary_const
    - unnecessary_parenthesis
    - use_string_buffers
    - avoid_returning_null
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - avoid_shadowing_type_parameters
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - no_runtimeType_toString
    - sort_pub_dependencies

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
  plugins:
  - dart_code_metrics

dart_code_metrics:
  metrics-exclude:
    - bin/**
    - test/**
  rules:
    - avoid-ignoring-return-values
    # - avoid-unused-parameters
    - double-literal-format
    - no-boolean-literal-compare
    # - no-equal-arguments
    # - no-magic-number
    - prefer-conditional-expressions
