include: package:lints/recommended.yaml

linter:
  rules:
    non_constant_identifier_names: false
    prefer_function_declarations_over_variables: false
    constant_identifier_names: false
    avoid_slow_async_io: true
    unnecessary_brace_in_string_interps: true
    unnecessary_await_in_return: true
    unnecessary_const: true
    unnecessary_parenthesis: true
    use_string_buffers: true
    avoid_returning_null: true
    avoid_returning_null_for_future: true
    avoid_returning_null_for_void: true
    avoid_shadowing_type_parameters: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    no_runtimeType_toString: true
    sort_pub_dependencies: true
    always_declare_return_types: true
    # avoid_dynamic_calls: true

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
  plugins:
    - dart_code_metrics

dart_code_metrics:
  metrics-exclude:
    - bin/**
    - test/**
  rules:
    - avoid-ignoring-return-values
    # - avoid-unused-parameters
    - double-literal-format
    - no-boolean-literal-compare
    # - no-equal-arguments
    # - no-magic-number
    - prefer-conditional-expressions
