include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - avoid_slow_async_io
    - unnecessary_brace_in_string_interps
    #- hash_and_equals
    - unnecessary_await_in_return
    - unnecessary_const
    - unnecessary_parenthesis
    - use_string_buffers

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
  plugins:
    - dart_code_metrics

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 25
  rules:
    # - avoid-unused-parameters
    - double-literal-format
    - no-boolean-literal-compare
    # - no-equal-arguments
    # - no-magic-number
    - no-object-declaration
    - prefer-conditional-expressions
